# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
